# Generated by Django 5.0 on 2025-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='bukti_pendukung/')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_generate', models.DateField(auto_now_add=True)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pengaduan', models.DateField(auto_now_add=True)),
                ('isi_laporan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bukti/')),
                ('lokasi', models.TextField()),
                ('status', models.CharField(choices=[('tunggu', 'Tunggu'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='tunggu', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_tanggapan', models.DateField(auto_now_add=True)),
                ('tanggapan', models.TextField()),
                ('status_pengaduan', models.CharField(choices=[('proses', 'Proses'), ('selesai', 'Selesai')], default='proses', max_length=10)),
            ],
        ),
    ]
