# Generated by Django 5.0 on 2025-02-04 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laporan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laporan.kategori'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'masyarakat'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporan',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.pengaduan'),
        ),
        migrations.AddField(
            model_name='buktipendukung',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.pengaduan'),
        ),
        migrations.AddField(
            model_name='tanggapan',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.pengaduan'),
        ),
        migrations.AddField(
            model_name='tanggapan',
            name='petugas',
            field=models.ForeignKey(limit_choices_to={'role': 'petugas'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
