# Generated by Django 5.0 on 2025-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='nama_kategori',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='tanggapan',
            name='status_pengaduan',
        ),
        migrations.AddField(
            model_name='kategori',
            name='nama',
            field=models.CharField(default='Default Nama', max_length=100),
        ),
        migrations.DeleteModel(
            name='BuktiPendukung',
        ),
    ]
