# Generated by Django 5.0 on 2025-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_remove_kategori_nama_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
