# Generated by Django 5.0 on 2025-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_alter_kategori_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='tgl_generate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tunggu'), (2, 'Proses'), (3, 'Selesai')], default=1),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='tgl_pengaduan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tanggapan',
            name='tgl_tanggapan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
