# Generated by Django 5.0 on 2025-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_alter_laporan_tgl_generate_alter_pengaduan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='kategori',
            field=models.CharField(choices=[('Kebersihan', 'Kebersihan'), ('Keamanan', 'Keamanan'), ('Pelanggaran', 'Pelanggaran'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Tidak Ditentukan', 'Tidak Ditentukan')], default='Tidak Ditentukan', max_length=50),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='lokasi',
            field=models.CharField(max_length=255),
        ),
    ]
