# Generated by Django 5.0 on 2025-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
