# Generated by Django 5.0 on 2025-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nama',
            field=models.CharField(default='Anonim', max_length=100),
        ),
    ]
